icons-format = "{icon}"

[theme]
theme = "gruvbox-dark"

# gruvbox-dark reference
#idle_bg = "#282828"
#idle_fg = "#ebdbb2"
#info_bg = "#458588"
#info_fg = "#ebdbb2"
#good_bg = "#98971a"
#good_fg = "#ebdbb2"
#warning_bg = "#d79921"
#warning_fg = "#ebdbb2"
#critical_bg = "#cc241d"
#critical_fg = "#ebdbb2"
#separator = "\ue0b2"
#separator_bg = "auto"
#separator_fg = "auto"

[icons]
icons = "material-nf"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit =  "GB"
interval = 20
warning = 4.0
alert = 2.0
format = " $icon root: $available.eng(w:2)"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%a %Y-%m-%d %R') "
[block.theme_overrides]
idle_bg = "#458588"
idle_fg = "#ebdbb2"
